CREATE TABLE IF NOT EXISTS donations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT UNIQUE,
    member_id INTEGER NOT NULL,
    receipt_no TEXT,
    donate_date TEXT,
    extra_no TEXT,
    amount INTEGER,
    summary TEXT,
    donate_note TEXT,
    other_note TEXT,
    donor_no TEXT,
    light_no TEXT,
    should_pay INTEGER,
    donate_type TEXT,
    creator TEXT,
    is_deleted INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    device_id TEXT,
    sync_status TEXT NOT NULL DEFAULT 'clean',
    FOREIGN KEY(member_id) REFERENCES light_members(id) ON DELETE CASCADE
);
